services:
  - type: web
    name: quickbooks-oauth
    env: node
    buildCommand: npm install
    startCommand: node server.js
    # Environment variables should be configured in the Render Dashboard
    envVars:
      - key: QUICKBOOKS_CLIENT_ID
        sync: false # Configure this in the Render Dashboard
      - key: QUICKBOOKS_CLIENT_SECRET
        sync: false # Configure this in the Render Dashboard
      - key: QUICKBOOKS_ENVIRONMENT
        value: production
